server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    thymeleaf:
      prefix: classpath:/templates
      suffix: .html
      cache: false
